### ISSUE TITLE
Vanced Manager bug/issue

### ISSUE THREAD

**Issue by kentify** [YTVanced/VancedManager#167]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Huawei
- Operating System: Android 
- Android Version: 10
- Vanced Manager Version: 1.2.0(Niko)

**Please describe the problem you are having in as much detail as possible:**
I encounter a bug that when you press the install button multiple times in vanced manager, the progress bar will constantly move forward and backward. Is it possible to tap it once only? 

**Steps to reproduce:**
Constantly tap the install button of either vance or microg in vanced manager.

**Further details:**
Here's the demo https://youtu.be/sGSf3OCYuIw

**Comment by KevinX8** [comment]
probably fixed in https://github.com/YTVanced/VancedManager/releases/tag/1.3.0

**Comment by kentify** [comment]
@KevinX8 I tried it today but still the issue persist. Hope will fix it in the next update.

**Comment by X1nto** [comment]
> @KevinX8 I tried it today but still the issue persist. Hope will fix it in the next update.

We have a boolean that holds the status of installation (true/false), unfortunately that variable doesn't get updated immediately but rather is updated on download start, unless we move it directly to listener it will behave like that. Now on the other hand the bug is not critical, as no user will press button multiple times because the download starts instantly.
