### ISSUE TITLE
Vanced Reverts to Regular YouTube App After Reboot.

### ISSUE THREAD

**Issue by znbaboy** [YTVanced/VancedManager#378]
**Phone Specifications:**
- Brand: OnePlus 7 Pro
- Operating System: Oxygen OS
- Android Version: 10
- Vanced Manager Version: 2.0

**Please describe the problem you are having in as much detail as possible:**

I am rooted with the latest version of Magisk on the date of this bug report. Everytime I installed the root version of YTVanced, it works fine until I reboot my phone. After reboot, the original YouTube app takes over and the Vanced version just uninstalls. There is no way to uninstall YouTube from my phone (tried Titanium Backup & ADB commands). Also, YouTube shows updates on play store even when Vanced is installed. For now, I am using the non-root version and its working fine, but prefer using the version that is meant for me. 

**Steps to reproduce:**

Install Vanced and reboot phone

**Further details:**
N/A

**Comment by X1nto** [comment]
A. newest manager version is 2.2.1, the bug was fixed there
B. #322

**Comment by lihuelworks** [comment]
Still happens to me 

- Xiaomi MI A2 LIte
- Stock ROM
- Vanced Manager 2.5.1
- Vanced Root version
- Using Magisk app/maanager 22.0 (Since that version they work as a single app)
- Android version: Android One

Same steps as OP.

**Comment by infinitewaveparticle** [comment]
@X1nto Has this been fixed (since @lihuelworks reported it was still happening in April)?

**Comment by X1nto** [comment]
> @X1nto Has this been fixed (since @lihuelworks reported it was still happening in April)?

there's a setting called "root script sleep time", configuring it will most likely fix the issue for 99% of devices

**Comment by lihuelworks** [comment]
> > @X1nto Has this been fixed (since @lihuelworks reported it was still happening in April)?
> 
> there's a setting called "root script sleep time", configuring it will most likely fix the issue for 99% of devices

I've tried setting it to it's max time , but it still has that problem (until Youtube Vanced it's reinstalled). It isn't a top priority issue of course, only a minor annoyance, so take all the time you need.

**Comment by X1nto** [comment]
> > > @X1nto Has this been fixed (since @lihuelworks reported it was still happening in April)?
> > 
> > there's a setting called "root script sleep time", configuring it will most likely fix the issue for 99% of devices
> 
> I've tried setting it to it's max time , but it still has that problem (until Youtube Vanced it's reinstalled). It isn't a top priority issue of course, only a minor annoyance, so take all the time you need.

Setting to max is a bad idea, I'd suggesting setting it to 2 or 3 at most. Keep in mind you also need Magisk for this and it needs to be updated to the latest version
